<?php
function clean_title($title) {
    $title = trim($title);
    $title = preg_replace('/\s+/', ' ', $title);
    return htmlspecialchars($title, ENT_QUOTES, 'UTF-8');
}

		
        $titles = [
'(Tomorrowlandspecial) Ahzee - King (Bass Boosted)', 
'4Motion - Take Me Away (Official Audio)',
'Acid Cry',
'Afrojack & Steve Aoki - No Beef',
'Ahrix - Nova',
'Alan Walker - Faded (Remix) ♫ Shuffle Dance (Music video) Electro House',
'Alex Gaudino feat. Crystal Waters - Destination Calabria [Explicit Version] [Official Video]',
'Alfons - Ganjaman (MIKE EMILIO REMIX)',
'Alien Cut - Cassone (Original Mix)',
'ALOK & Ilkay Sencan (feat. Tove Lo) - Don\'t Say Goodbye (Lyric Video)',
'Alok - Don\'t Ya (4Motion Remix)',
'Alok x Mondello x CERES x Tribbs – LET’S GET FKD UP [Techno Extended]',
'ALORS ON DANSE (Dubdogz Remake)',
'Aly & Fila - Rebirth (Ahmed Romel Remix)',
'Anya - Beautiful World ( Seaven & Oski Bootleg )',
'AREA21 - HELP (Official Video) @AREA21',
'AREES - Let\'s Go (Orginal Mix)',
'Arimasen, lostlight - fearless',
'ARMNHMR & PASSPORT FT. KELIZA - GONE (YUSSI REMIX)',
'Art of Cocaine (Melodic Techno Mix)',
'ARTBASSES x Skrynsu - Love In The Music (Original Mix)',
'Artemas - i like the way you kiss me (TRAVYP Techno Remix) [Extended]',
'BANGERS OF TECHNO  Remixes Of Popular Songs  TECHNO BIO GIRL #ravetok #techtok',
'BARE - Trooper',
'Bass House Mix 2019 #1',
'Bassline UKG Mix 2019 #4',
'BEAUZ - LICK IT (Extended Edit)',
'BEKA KSH - MIJAM',
'Besomorph - Monster',
'Best Car Music Mix 2019  Electro & Bass Boosted Music Mix  House Bounce Music 2019 #24',
'Best Car Music Mix 2021  Electro & House Popular Songs Mix  Club Future House Bounce Music',
'Best Music Mix ♫ No Copyright EDM ♫ Gaming Music Trap, House, Dubstep',
'BICEP - GLUE (Rialians On Earth Remix)',
'Binary Finary - 2000 (Jam X & De Leon\'s DuMonde Remix) - Trance Energy',
'Blastoyz - Mandala',
'Blazy - The Chase (LSD Trip Video)',
'Blinders - Leaving',
'BLR - Comfort Me (feat. MVRT) [Official Music Video]',
'Bobby Flexter - Profondo Rosso - Trance Progressive',
'BORGORE & SIKDOPE - Unicorn Zombie Apocalypse (Original Mix)',
'Boris Brejcha - Spicy feat. Ginger (Official Video) [Ultra Music]',
'Brattiputy -  Yeri Mua, Uzielito Mix, Jey F, Alan Dazmel, El Gudi, Oviña  (Video Oficial)',
'Breath - Hardstyle remix',
'Bring Me To Life (Teminite & The Arcturians Remix)',
'Bro Safari - Follow [Zomboy Remix] (Official Audio)',
'BURNS - When I\'m Around U (Official Music Video)',
'BVX - Step Back (Official Music Video)',
'CamelPhat & Ali Love ‘Dopamine Machine’ (Club Mix)',
'CAN\'T GET YOU OUT OF MY HEAD (TECHNO)',
'Car Music Mix 2016 Electro  House Bounce  Party Mix #8',
'Carnage & Borgore - Incredible (Original Mix)',
'Castle in the Sky - DJ Satomi',
'Cazz & Matson - Fucking with my head (Original Mix)',
'Cazz & Re Cue - Lick It (Orginal Mix)',
'Charlie Puth- We don’t talk anymore [remix] (slowed)',
'Charmes - Fulfill (Official Music Video)',
'Charmes - What\'s Up',
'Chemical Surf - Hey Hey Hey (Original Mix)',
'CHRIST - Falling   [Short Audiovisual Art by Karl in Sky]',
'Cinema - Skrillex',
'classic nightcore playlist',
'CLiQ - Clap Clap (Will K & Jebu Remix)',
'Cloud Seven - Come To Life',
'Club Disciples - Fly (DJ Gollum & DJ Yanny Cosmic Commando Remix)',
'COME WITH ME - Special D',
'Contiez Feat. Treyy G - Trumpsta (Djuro Remix) [Safari Music]',
'Creeds - Push Up (Official Video)',
'Crew Cardinal feat. Kodie - Money Can\'t Buy (DJ Gollum feat. DJ Cap Radio Edit)',
'Crew Cardinal vs. DJ Gollum ft. DJ Cap - Talk to Me (Hands Up Radio Edit)',
'Cristian Marchi Feat. Luciana - Keep Calm & Twerk On (Lyrics Video) - Time Records',
'CRW - I Feel Love (DJ Lewy & DJ ALC NightBasse SHORT Remix 2015)',
'Curbi - Spiritual (Mriya) [feat. Brooke Tomlinson] (Official Lyric Video)',
'D - Dial M For Moguai - Beatbox (original)',
'Da Tweekaz & Refuzion - Because Of You (Official Video Clip)',
'Daisy Dee -- Open Sesame (Kay Cee Remix).wmv',
'Dancin AMV - Aaron Smith (Krono Remix)',
'DaniAll - Dance Floor (Radio Edit)',
'Danimal, Heleen - ALIVE [Extended]',
'Dave 202 - Rain Against Her (Original Mix)',
'Dave Spoon feat. Lisa Maffia \'Bad Girl (At Night)\' (Original Club Mix)',
'David Guetta - Sexy Bitch (Jesse Bloch Bootleg)',
'Deadmau5 - Ghosts N Stuff (Nero Remix)',
'DeeFresh & Mr.Cheez - Carnage (Orginal Mix)',
'Deekline and Wizard - All Your Love',
'DEJS - Close To You',
'DEJS - FACEBOOK',
'Delerium ft. Sarah McLachlan - Silence (Martin Vide Bootleg)',
'Discotronic - Now Is The Time (DBL Future Rework)',
'DJ Antoine  - Ma Cherie (PLAX Bootleg)  FBM',
'DJ Antoine & Darius & Finlay - Do It All Night In St.Tropez (Phobia & Shaker Bootleg Mix)',
'Dj Antoine - C\'est La Revolution (BUENO CLINIC x HUHERKO REMIX 2019) FREE DOWNLOAD!',
'DJ Arne L II + DJ Mirko Milano - Freak In Me',
'Dj Bazz - Andre & Michelle (Original Mix)',
'DJ Cringey, DJ Kirby - So Lost (Official Music Video)',
'DJ Fresh & Adam F - Believer [David Zowie Remix]',
'DJ Fresh - Gold Dust (Flux Pavilion Remix)',
'DJ Kaka & Kamilos - Alkohol (Original Mix)',
'DJ Kaka - We Think It\'s Cool (Original Mix)',
'DJ Misjah & DJ Tim  - Access',
'DJ Misjah - Keep Your Love',
'Dj Panda - Dreaming of Fantasy',
'DJ Phil TY - A Kay A (EHM Mix)',
'Dj Raaban - Be Alive',
'Dj Satomi - Flying High',
'Dj Satomi - Waves',
'DJ Satomi - Wonderland',
'DJ Snake & Lil Jon - Turn Down For What (Onderkoffer Remix)',
'DJ Tiesto - Adagio For Strings',
'DJ Tiesto - Welcome To Ibiza',
'Dom Dolla - Take It (Extended Mix)',
'Dynoro & Gigi D\'Agostino Vs Guru Josh - Infinity In My Mind (Djs From Mars Bootleg)  FBM',
'Dynoro & Gigi D’Agostino - In My Mind (Harlie & Charper Bootleg)  FBM',
'Egohead Deluxe - Turn The Lights Off (Cuba Club Radio Edit)',
'Eitan Reiter & A Balter - iRich',
'Ela Rose & Gino Manzotti - No U No Love  ( CLIMO Bootleg )',
'Emalkay - When I Look At You',
'Emok & Morten Granau - 3rd Eye (Ritmo Remix)',
'Empire Of The Sun, southstar - We Are The People (southstar Remix) Official Visualizer',
'Empyre One Feat. Enerdizer - Next World ( Official Anthem) (Club Mix)',
'Erika - I Don\'t Know [Official Video]',
'Excision, Datsik, Dion Timmer - Harambe [Official Video]',
'Exploration Of Space - Cosmic Gate & Space Case - Armin Van Buuren (Momentix Edit)',
'Fabio Fusco - Your Spot (Official Audio)',
'Fagget Faireys - Samo Ti (Julas & DJ Salis Bootleg)',
'Far East Movement - Like A G6 (Trafoier Remix)',
'Flux Pavilion - I Can\'t Stop',
'Franky Nuts - All I Want',
'Fresh \'n\' Sexy (Extended Mix)',
'FTampa vs. Throttle vs. DJ WAJS - Baby Behavior (I.GOT.U SMASH)',
'Funkwell - Shake This (Original Melbourne Mix) 2013',
'Gaia - Tuvan (Original Mix)',
'Ghost Rider feat. Kathy Brauer - Only One (Official Lyrics Video)',
'Gigi D\'Agostino - La Passion (Dawson & Creek Bootleg Mix)  FBM',
'Give It To Me (Techno Remix) [Extended Mix]',
'GOD\'S PLAN (HOLY GOOF BOOTLEG)',
'Good Vibrations (OffBeat Progressive Trance Set) 2017',
'GotSome feat. The Get Along Gang - Bassline (Main Mix) [Cover Art]',
'Gouryella - Gouryella',
'GRAViiTY - The Passenger',
'Habitanto - SAD',
'HARD-PSY  JEEX & Astrokillerz - Release Me [BHM Exclusive]',
'Hardwell & Blasterjaxx feat. Mitch Crown - Bigroom Never Dies (Visual Video)',
'Hardwell - Spaceman (Original Mix)',
'Haru Chill EDM Mixes 𝟰𝗞#electronicmusic #music #musicgenre #nightcore #edm #slowedandreverb #mix',
'Haru Nightcore Mix 𝟰𝗞 #electronicmusic #music #musicgenre #nightcore #edm #mix',
'Haru Nightcore Mix 𝟰𝗞 ~ Lilly`s Track iykyk ~',
'HBz - Not Fair (Bounce Mix)',
'Hurdslenk - Futures [HARDGROOVEDIGI028]',
'HYPER MOOD - Stay or Leave (Hypertechno) [Extended]',
'Indira Paganotto - Himalaya (Original Mix) [KNTXT013]',
'Inna The Best of MIX 2K12 Shomi DJ',
'Insigma - Open Our Eyes (Alex M.O.R.P.H. Remix)',
'Internet Autism Mix',
'IVOXYGEN - plateau (angst Remix)',
'IVOXYGEN - plateau (angst Techno Remix) [Extended]',
'Jacob Tillberg - Ghosts',
'Joey Beltram - Energy Flash  -  R&S Records Classics',
'Johnny Vicious Featuring Lula - Ecstacy (Take Your Shirts Off) (Chelsea Mix)',
'June Valley & @W4lliam - Neon Hype [Dubstep]',
'K.Flay - Can’t Sleep (RNR Bootleg)',
'K.Flay - FML (RNR Bootleg)',
'Kai Tracid -  Suicide',
'Kai Tracid - Trance & Acid (Official Video)',
'KARIX & MATSON - GOOD DAMN (ORIGINAL MIX) + DL',
'Keep Your Love',
'Keys N Krates - Dum Dee Dum (JiKay Remix) [OFFICIAL]',
'kina can we kiss forever (TikTok Version)',
'Kisloty People',
'Kit Hype - In My Head (Hardstyle)',
'Klubbheroes - Poco Loco (Extended Mix)',
'KORDO - Holy Moly (Original Mix) [FREE DOWNLOAD]',
'KSHMR & 7 Skies - Neverland [Official Audio]',
'La Roux - I\'m Not Your Toy (Nero Remix)',
'Laidback Luke & Moska - Get it Right (ft. Terri B!) [Official Lyric Video]',
'LET\'S GET FKD UP (Strong R. Extended Techno Remix)',
'LET\'S GET FKD UP Strong R. Remix',
'Lethal Industry',
'Light It UP!',
'Lights - Ellie Goulding (Dubstep Remix) [HD]',
'Lilianna Wilde - Grind Me Down (Jawster Remix) [Fantasize Meme Flipaclip Song]',
'Lock \'N Load - Blow Ya Mind (Club Caviar Remix) 1999',
'Lucky Luke - LYD (Like You Do) Future House',
'LYBERTYS',
'Majlo - Bang (Original Mix)',
'Majlo - Radiation (Original Mix)',
'Majlo x Gazell - Let It Drop (Original Mix)',
'Majlo x Kofm - Nasty (Original Mix)',
'MAKJ & WILL K - Bounce 2 This',
'MANDEE & Older Grand - Watch Out (Original Mix) [BP001]',
'Maniacs Squad - Get That (Original Mix)',
'Maniacs Squad - Stop (Original Mix)',
'Manian - Ravers in the UK',
'Mario Piu & Mauro Picotto - Imperiale',
'Mark OH - United ( Seaven Bootleg )',
'MaRLo - Enough Echo (Official Music Video)',
'Marnik - Up & Down (Kaka Refresh) 2019',
'Martin Garrix & Firebeatz - Helicopter (Original Mix)',
'Matson & Sound Bass - Motherfuckin (Original Mix) + DOWNLOAD',
'Matt Nash - Know My Love (Official Music Video)',
'MaxRiven - Yeah Yeah Yeahs',
'Meduza - Piece Of Your Heart (Andry J Private Remix)  FBM',
'Meg & Dia - Monster (DotEXE Dubstep Remix)',
'Meiko - Leave The Lights On (ReliQium Hardstyle Bootleg)  HQ Videoclip',
'melodic Dark Techno',
'Mike L & B3nte - Go Bananas',
'MMV -  Aftermath - The way You Are',
'MMV- Imanbek – RosesRemix',
'Modjo - Lady (Hear Me Tonight) (Radio Edit) (HQ)',
'Morten Granau & Emok - 3rd Eye',
'Mr. Belt & Wezol, Freejack - Somebody To Love (Silence x Re Cue Bootleg) 2019 HD!',
'My Radio (Phillerz Radio Edit)',
'Mylène Farmer - Oui Mais Non (SM LY Remix)',
'Naturalize - Faithful Souls (Official Audio)',
'Neelix - Alone After All Mix (Official Audio)',
'Neelix - Alone After All [feat. Vök, Caroline Harrison] Live Mix',
'Neelix - Let\'s Just Leave',
'Neelix - Makeup (feat Caroline Harrison) (Blazy Remix) [Official Audio]',
'Neelix - Makeup (feat. Caroline Harrison)',
'Neelix - Not The One (feat. Caroline Harrison) [Official Audio]',
'Neelix - Time To Wake Up (Official Audio)',
'Neelix, Caroline Harrison - There Was A Time (Official Music Video)',
'Neelix, DayDin, Kronfeld, Morten Granau, Durs & Nok!!! 2017',
'Neelix, Ghost Rider, Caroline Harrison - The Sun (Official Audio)',
'NEXBOY - WANTED (Crouzer Remix)',
'Nicky Romero - Lighthouse ( Sound Bass VS Seaven VS Mr Matt 2018 )',
'Night Club - Show It 2 Me (Official 360 Video)',
'Nightcore  1 Hour Of Cascada Classix',
'No ID (Belik Boom Remix)',
'NoizBasses - I\'m The Sexy Girl 2019 (Original Mix)',
'OMFG - Hello',
'Omiki - Na Le (Official Audio)',
'Out Of Grace - Anglia (NEXBOY & DBL Bootleg)',
'Paffendorf - La La La Girl (MIVVO & Re Cue Bootleg)',
'Paffendorf - La La La Girl (Official)',
'PAWEU & TOPS - COMO! (Original Mix)',
'Phaxe & Morten Granau - Beatless',
'PHAXE & MORTEN GRANAU - LONG STORY SHORT (STATIC MOVEMENT REMIX) - MᵉʷˢᶤᶜUᶰᶤᵛᵉʳˢᵉ',
'Phaxe & Morten Granau - Swarm (Official)',
'Phaxe & Morten Granau - The Collective',
'Phaxe - Disturbed',
'Phaxe  Querox  Morten Granau -  8 Mile Collective',
'Phaxe, Morten Granau, Vaishiyas, Audiomatic & Kularis!!! 2017',
'Phillerz - Get It (Radio Edit)',
'Pimp Code - We Are The Best',
'Pixies - Where is my Mind (WhyAsk! Remix)',
'Psy Or Die  No Money (Armin Van Buuren Mashup)[Branwell Remake]',
'PSY-TRANCE  Flo Rida - Right Round (Konaefiz, Thorment & Mahori Remix) feat. Ke$ha',
'PSY-TRANCE  Imagine Dragons - Believer (Flash Jack Remix)',
'Psychedelic Trance mix  2019 2020  part I [135bpm - 137bpm] best of the decade mix',
'PSYTRANCE • Blax & Neo Flux - Wherever You Are',
'PUT-IN - Cukier Drożdze Destylacja ( Oficjalny Teledysk )',
'PUT-IN - Kotecek ( Ra Pa Pa Pa Pa )',
'PUT-IN - Piosenka o Białym Misiu ( Oficjalny Teledysk )',
'PUT-IN - ŚWISTAK ( Prod. Judasz )',
'QBIK - 4 Pory Roku',
'Quench - Dreams (1993)',
'Rafter - Chasing (Bass Boosted)',
'Ranji - Butterfly',
'Ranji x Omiki Ft. AVIVA - Psycho (Official Video)',
'RAVER QUEEN TECHNO MIX 2024 BEST SUMMER TECHNO MUSIC',
'Rawtk & Hot Light - Give To Me  Music Visualization',
'REBOUND X - RHYTM & GASH (SICKBRAIN REMIX) FREE DOWNLOAD',
'Rebuke - Along Came Polly',
'Redondo - Instant Moments',
'Roberto Kan - Alive (KEAN DYSSO Edit)',
'Rocco - Everybody (Club Mix)',
'Rocco - One Two Three (DJ ENDRIU BOOTLEG)',
'Rompasso - Angetenar (Original Mix)  #GANGSTERMUSIC',
'RUNAWAY (TECHNO)',
'Santogold - You\'ll Find a Way (Switch + Sinden Remix)',
'Scotty Boy - Melbourne (July 22nd)',
'Sean Paul - Get Busy (Loutaa 2 A.M Remix)',
'Seaven vs. DJ WAJS x Bartii - Revolution Disco Music',
'set fire to the rain tekkno',
'Shanguy - King Of The Jungle',
'Shanguy - La Louz (Maniacs Squad & Prisoners Show Bootleg)',
'Shiva Style (Berg, Phanatic Remix)',
'Showtek & Justin Prime ft. Matthew Koma - Cannonball (Earthquake) [Lyric Video]',
'Showtek - We like to Party (Radio Edit)',
'SICKBRAIN - BANGER',
'Sikdope - Snakes (Official Audio)',
'SILK - When A Fire Starts To Burn',
'Skyper - The Flight (Why Love Me Meme song)',
'Sonny Wern - Dance For Me (1, 2, 3) [Extended]',
'Sound Of My Dream (feat. Yoshica)',
'Southstar - We Are The People (Southstar Remix) [Extended Mix]',
'Spinus - Alligator (Bass Boosted)',
'Steradlye - Devilish Heart',
'Steradlye - Purr Bass',
'Stonefox - Lightning (Ghost Rider & Ranji remix) Lyrics Official Video',
'Styles & Breeze - Your My Angel (Midnight Mix)',
'Swedish House Mafia - One (Original Mix)',
'Symbol- Silaver (The Asterisk War AMV)',
't.A.T.u - Nas Ne Doganyat (Silence Bootleg) 2019 HD!',
't.A.T.u. - All The Things She Said (Rusty Hook Remix)',
'TAITO - Fifty Fifty (Official Video)',
'TCM - Crash and Burn (Hardstyle)  HQ Lyric Videoclip',
'Techno Disco!',
'The Aphex Twin - Digeridoo (1992)',
'The Chainsmokers - SELFIE  Car Music Mix (Car Race Video Mix)',
'The Road I\'m On (Omiki Remix)',
'The Source - License To Dance',
'Tiësto & KSHMR feat. VASSY - Secrets (Original Mix)',
'Tiësto, Oliver Heldens - The Right Song ft. Natalie La Rose (Lyric Video)',
'Tobias Bassline - Supernova [Progressive Psytrance Mix 2014]',
'Top 5 Best of Alan Walker ♫ Nightcore Alan Walker',
'Trance - 009 Sound System Dreamscape',
'True Blue (HyperTechno) [Extended Mix]',
'Tujamo & Plastik Funk - Rocky Who (X-Seb Rework)',
'UK Bass Bassline Jackin Mix #3 2019',
'UNLOGIX - Paradise (Skyfall Remix)',
'Vibey Deep House Mix',
'Vicetone & Tony Igy - Astronomia',
'Volac - Open Your Mind',
'Vök - Before (NEELIX)',
'W&W and Groove Coverage - God Is A Girl (Official Video)',
'Walking On a Dream (Techno Remix) (feat. Zyzz)',
'Waveshock & TWISTERZ - Body Flow (Official Music Video)',
'Westbam- Agharta 2010 (Waveshock & Radi S. Remix)',
'White Sky',
'WHITENO1SE & Ranji  Ft. Nina Nesbitt - The Moments I\'m Missing  (Radio Edit)',
'WHTKD - Say To Me (Official Video)',
'Will Sparks - Ah Yeah So What (feat. Wiley & Elen Levon) (Bass Boosted)',
'Will Sparks Style 2022 - Techno & Melbourne Bounce & Psytrance Music Mix',
'Xenaan - WITH YOU',
'Xillions - Somebody Like Me (Mark With a K RMX)(Official Videoclip)',
'XYLØ - Afterlife',
'You Make The World Stop',
'YouNotUs, Janieck & Senex - Narcotic (Mark Star Bootleg)  FBM',
'Zeds Dead - White Satin',
'[Hardstyle REMIX] Black Identity - Blacker Than Black (The Prophet vs JDX)',
'Время и Стекло - ТОП [Lyric Video]',
'Я люблю хардкор'
        ];

        $youtube_ids = [
'Ex9Pr1GjcxQ',
'b6KoOHqtKgo',
'DYQC0SRi1oA',
'JOsmEpLI0Cc',
'6AaoDvxqE74',
'1oTUupME0-M',
'Kq4OtRsdXls',
'R2yAMinLXig',
'yfAydckyb-A',
'Q-T7Mp-OPWw',
'9_OzQ5GDV3o',
'QlSGBQ0kscM',
'y853iY0tyS4',
'_MNe7-mZx_8',
'hPFmd7isXeg',
'yaqTZiqYvf4',
'l4B9jRVtI7M',
'8IsFq_slWpM',
'3nT0ZEQ0OCI',
'B4f_kLVdi3Q',
'9DFmDYeOlf8',
'f7sn7zctO_c',
'S2M4gxzaT1E',
'FXWOY6vc3bA',
'19erorrU5nM',
'omNH0C11pew',
'LC_FdVkjSMQ',
'KyTbR3zzd4I',
'7Q_UwqjpfMA',
'fXXbXECr8QA',
'O0Pb6i0OAmY',
'LaQj636PJh0',
'qpfJRZfuesU',
'raOfvIzZviM',
'FHVD9ft_ANw',
'EQMHN6qfoBI',
'CHVh2JsXnOk',
'tFU2nhcu2Fs',
'KxzOUxGx688',
'UyI4v5sxT54',
'5Ep8M8D8mkw',
'f0OnAxrOWyw',
'VkdX3XyC1Jg',
'Viwd2P5fJZA',
'RN8oC5LfNdQ',
'ubkWrjeCNGI',
'xOWfaMN9jk8',
'o3F4xZfIIJU',
'7QXDkrkdmc8',
'FgOs8YG9LRk',
'i8nYBqPRNKw',
'K-PdbfkA7LM',
'Je7ByfcgkxQ',
'OnK1pAnk2aE',
'-dPW5hFGQ8w',
'aOz4lQJb_PA',
'FIwKjN6prs0',
'Hn3qkgvVgeo',
'aj21obFUyNU',
'QQcQDbpDH_o',
'TioXXhcLinw',
'as0gqdxGn0o',
'p9LlU6Zd9MY',
'ab7VfZgCRlk',
'7KgJSwX0yy0',
'0RiQDCWsk-U',
'_yMN6hxyOTM',
'KQn-HWjrG5c',
'DKyvVqCBDBE',
'CGwwkak7zPY',
'IK5Cr9-HZVk',
'vLaJoDxvA0M',
'UZ1Fq44X_fk',
'jgj0qbMgxNc',
'pnYrkSrczcc',
'_ILuM2RiqYY',
'LvyX8JqI_oc',
'BQSYa2Wlw_Q',
'W0CtcOXYT6E',
'W4SN_aC8e9E',
'MLsMK21Sz-M',
'3Gb3faOzvBk',
'aAsB2Re5cA8',
'Ne3GGwq0H8w',
'XgAIi3uk0rE',
'1YvWyUQB3h0',
'CemQxI2-4Gc',
'68T9EZc0mLE',
'hsaAwDD3FjU',
'8QgnbY7VoeM',
'pXbnRcViELA',
'Y3piVyT1nCA',
'OYi528yo81U',
'I8iJXz0x_NU',
'ddHQVymC3ds',
'PEbJ4qLiMu0',
'l31-bb2PgNU',
'uK3Fr_MlKJ0',
'4o4joooH5tg',
'UlP-L7aIbZk',
'sfifcz99A7o',
'bXXNEeU1IDg',
'idzILJkuje8',
'ivB12j7TiXs',
'EYSYLt14miM',
'gNQpyrGwmgw',
'CES32EOxiyw',
'8tIgN7eICn4',
'HHnXiPJ4TOQ',
'NcS9OkHyB0w',
'5wYJ36fZgTo',
'vQ19OpA9qGc',
'NaN7o5PkGMg',
'4cMPQa4MCuk',
'B25hMaz7tAI',
'_mwL6R-Z1e4',
'i3hCjskWnRM',
'qguEGR5BK2k',
'3jx8kGotMAk',
'VVuQp14fy20',
'uP7FZdeaCu8',
'x-dKIQi-oD8',
'-3f7CJsCroE',
'tFF4bp14eqE',
'ThqAIy147CI',
'3Q9rewnLFYw',
'4UbPK9DHetM',
'ymevfoMRESc',
'XPh1Zk-t1P8',
'nH6YVXWzNcM',
'NcPg80JqNX8',
'0UZZmLfB2As',
'ULLPTxgephw',
'X1ZkWwDLwZI',
'aUpsfWSI8qc',
'lfumW5RCRJ4',
'cnsWOnQbF4Q',
'NEivFBrGESk',
'I17Da5m1wvA',
'xQDhJRjsIao',
'gIurg3znADE',
'4IHDZ4_8oN0',
'7ty7mk3UOmo',
'IIEfsJnN2k0',
'PaSvL_fCSvo',
'_eYSt2WgrOg',
'Yyja_rbyifY',
'IfH__tR3Rvo',
'8F4Gv-_lvBg',
'qubVw5fVW-U',
'Km-Lczsoj2Q',
'vT_zkD83sgw',
't7jg83-HcO0',
'-ONbRjc7Qs0',
'wed87yyVNcM',
'vJyR2QpHGvc',
'ALsHox5sYCk',
'T6NhRms3CDA',
'mrGtLBleHpY',
'Wdr6-KzvKk0',
'JdDDaJAaQYU',
'qhD0V1qE9rI',
'DBAQRY1MTUY',
'lw4vj-Dyyys',
'uPXh_L6vVe8',
'Dg6HQ8RlPGQ',
'1-3B4sbjDHg',
'DJ2fjjhVzBI',
'1rbJ0eoRVt0',
'-C0xX5g_RCI',
'9hUWxoDtHmE',
'Q3Cm69gtd4E',
'Gz8cPlh-kP0',
'MgfEKA0G9Q0',
'lybsyH5A86A',
'9EeWQFxLma4',
'jtK0GSZX_Lw',
'J0vIEn0XSBA',
'QJSfieToXSQ',
'ryFmAc3C0pw',
'4TNAQfC5jB4',
'NaffWNBMlHo',
'Dz0Id3j3d14',
'DyA5CR77DeM',
'tAxYG9PaXsQ',
'WUL89ns3esc',
'ebaKzsKnnjA',
'aiyoJ_7Ft-A',
'rxeRSV1yEGE',
'QkDLf3rV02Y',
'F8bDlKZqGgA',
'aHoH7D_7wdA',
'a27MCWZOKJw',
'a59HMm-3fwk',
'jYjnQPd33NA',
'4zYma0jF3oM',
'ovDcLHa2L1o',
'IlFGN-7Ws98',
'fb0ikUyMWbI',
'C_zjOUaSGqQ',
'VQsKJTHTjmc',
'-0oZNWif_jk',
'7EUGClVXoMw',
'aBLWvHlwzsQ',
'3P1odnWrLiQ',
'ByaOT2wPLV4',
'puCbbITNhT8',
'vRB1MLGEHSc',
'h4tkLbWMH-k',
'tiUb194mId4',
'hbL4-YEPgNU',
'XIxFULlIDXE',
'KUXowTmXTJk',
'mWEgqFnnvGw',
'Ir-ErHFxfLE',
'6jkN8DsjsYQ',
'hjchUfrnfTg',
'QZl_eDXxVAA',
'9dxBX_fh3Oo',
'Fr2ANun0IPo',
'A0cYgqi2eGs',
'SLJbGTLj65E',
'kvnUIxSXE_M',
'KaWhuhAIL6w',
'zNcjsYeUjuQ',
'JtYa0rb_jGQ',
'MYs3wuvNl8k',
'dqTSunQkeiQ',
'GtTH1jDUn6o',
'ih2xubMaZWI',
'UigXTja6s6o',
'c_F-cxIWRAY',
'cQj16Wwym7A',
'jdH0BM_ph0w',
'0tbTsq3wIp8',
'4vKo-ApcKgE',
'BwbyuHWFTtA',
'o2Zb49OVpto',
'aTdyT2M9-3o',
'8YotLOeRLVw',
'StpTfBonPA0',
'R-3pnfonPmg',
'PnHTEDUAnGk',
'0a81rYhRlbA',
'xsRPz9PF1EE',
'hg2ZDMhdI_8',
'V0W2QJ7uL70',
'QMrhFkPrXhY',
'JK1NEy1ZilE',
'JVo07HLingI',
'eKRQqgFvqA4',
'NXF79Qc3LjY',
'e_ooxjzzR0o',
'bZTGDK6MJ60',
'9y8sZ6bZtaA',
'OqxLwjMAny4',
'CY2_jspA-MU',
'XgF2l3I840Q',
'S9F27KR0TJ8',
'VP3prc5TWH8',
'M8YIGNdm0rw',
'Z1S9fheoblI',
'-kLvsKZMLh4',
'NT7qxvX9uNg',
'QDESrck_6LQ',
'03RaZ39URU4',
'kkDqQ0Qwies',
'OZafwTE1q4Q',
'bID5Srt_YDA',
'VnAQL-VL3w4',
'Sjbf1b8uNug',
'2roXL3-YLRE',
'OgRJQrPRBWI',
'qYpHFS0oGnY',
'eB6VpP3IN38',
'nmoIY2_KUlw',
'_bxq-YQgUqo',
'ZwOVOSi-5nc',
'6KYq1Vjv-PU',
'JVEk-nZmE1U',
'nuGuqYNC4HU',
'7eiDGcRWId8',
'YYgjetNMfoM',
'yIx16BceKrk',
'om2nT_VkMpk',
'CxDWspTstUI',
'waMdzIJ1Edk',
'01LHUIGEMSM',
'sxfcKRkS1WI',
'wR4E4ESvMdc',
'l1Cvvx9MFsc',
'dg7XO1zgJHA',
'hyJ1u_Ogfbc',
'u95i7uigeG8',
'0RxZ2u211OU',
'4RaTY2zz98g',
'RMNIHEnOSbI',
'0GdslNxmixw',
'8BGTvxxKoHM',
'qIhu-NTOo0U',
'qvmC4cpLG1s',
'RK86XxNLwjQ',
'EFU_LIzIfyw',
'bb1K0oML4ks',
'_gp51lt9kdA',
'kJsIyLsKiR4',
'2WPCLda_erI',
'_P7qUI6qYSc',
'ceuleMF1xCQ',
'DCLam3RsWBA',
'oxQ2twFKH2M',
'vXYXHHYdwTo',
'iLBBRuVDOo4',
'0KJHH08FPpE',
'642L9aFuD1g',
'ucs1af3Ntf8',
'EConX2hhuuY',
'uwRcdafEzus',
'KZeBfmJSwas',
'95x0q6rbd1M',
'otxSf5gsCNY',
'CYoPOJCeJvU',
'kqpyv73nPVE',
'sMKvW7qBXkQ',
'Nu1_C156178',
'b6NCaD9LjrI',
'BR74ZadqjNA',
'uBVSkJevtgM',
'zP-ksN4bKMo',
'wWC_WZ7gd6g',
'46lQoD5duf4',
'0E4aYgKmIko',
'21-A0j7kA3w'

        ];
		
		
		$mega_links = [
	'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/hM5E1SCB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/VchgiYpK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/8E4ETQjS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/VFwWlYKb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/hE4AyChT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/RRhiBQLA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/xJpCzQbS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/UM5QDAAY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/xZpw3C6Y',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/AJoUTSxB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/FA4ADQIL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/FRww2KDT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/EBgkBYgC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/9dgGnK5S',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/wJ4AmAyT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/sYogACTS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/YQoADYxI',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/NU5GnSya',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/8BgyHQwZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/8MoUzQIK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/NYhkHQyQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/MQgExaJR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/MJhkWagQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/xQ50gCoQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/NZ5WXAZC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/8Ax2GYAC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/0V5gQKSa',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/BNx2gKSI',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/ZB5yRYqZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/FYwUFCbB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/YEwEAaDZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/xcw0hYBB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/xE4U2QhA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/lEokHaBb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/MR5WiC6Y',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/ME5UFKLZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/9N4mkaaY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/QM4EnA4R',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/hdokkIjR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/sM5GXQ7B',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/YRpGEACS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/hQ4AhCYB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/MM40EYLQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/hAgUCAzQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/NchUzSZb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/tJhATAAZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/sJ4AmIhA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/kc50EKLA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/gAgSjAQY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/cUpWAAaT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/Yd4AiQIC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/Ecok2K6B',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/9UwyCSBT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/EMhwHKYb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/AZ42XazI',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/tdhAQCSK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/kNpykICC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/IJhQXABT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/dJgmzKjB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/4AgChQaa',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/AR5SgCAB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/NFwGXSxK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/RBomGSwY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/5QomkQLC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/oZoAmAiJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/dBpmFQIR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/1RxAVKxD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/lUxm2QjJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/AIw2QSLR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/5c42nCgJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/JI4w1IoK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/MIw0TATA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/8F4UzQjA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/hAggDaxK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/AchkGISC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/pF4mgKrL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/pRgSjI7Q',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/gF4khISY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/8B4wmIiA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/YE5g1SgB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/gE42XQBY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/ZJoGkQyJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/wd5GxSga',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/gcx2HAyL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/oRpWAAxK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/VNpCEYyb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/MQwCSSJb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/wQx0xIRa',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/QR4U2YhY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/odhyxCLL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/IVxkTQxD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/lJoUCYpY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/4F5yAIaD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/oBoWWYxY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/9VokUQqT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/sYwETSKb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/EIgw2AbL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/Acwi0YSR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/sN5GBACD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/NBp0nIhL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/wQ5AjKJb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/tEoSxaqL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/QApEESxR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/4Exg0SIL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/IAggnaiZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/VUxySI7B',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/QcxQQQZR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/UYoSHYjJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/8do0Ca7C',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/cFwWESKC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/ddwAkQID',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/UFxQ3A4B',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/NYwwlQRb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/wd4SAQDJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/YBwyVCqJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/pAwigaBQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/lV4UGKiB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/sRhUmYZb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/VMpQGCgA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/9RhSHI7L',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/0RxSHITD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/ZFwU0STb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/IYhgnCiB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/xA5gDIzK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/YIok2SAD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/xV5wSCzT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/Ydh2XSRZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/4EpSUabR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/dA5gkIpD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/5ZoC2IoJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/IYpmTAYD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/0Ap2mA7B',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/9RxQgawC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/Vdom2YoJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/VNx0RIbK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/QBwgiA6Q',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/AJoCiITa',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/VdwSVCgC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/AVhS3CLb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/ZdwQQC6I',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/wF4ABIAR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/NIwkgSrB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/QVwWlYxD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/QQhgkYzL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/QVoG2Yoa',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/oY5wyQwI',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/FYp2jQ4A',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/gNw2GaRI',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/VJhSWIDK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/dN4iDSAZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/8A401YQK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/gFgQXA5C',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/9EoE2SgB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/AZpWwKCC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/oNwwTQSR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/tQ5WEazB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/lQgkDIJZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/BE5SBIZI',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/wcgWiCTR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/wQpkma4L',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/1dgUTISQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/pZgCzAYa',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/BJ52xSbS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/dZw0RSJJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/gQgkRQgZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/5Mo0ySTC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/cFh2wAbZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/ld4SiCzb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/4Yh0zIxY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/IF5SiCwZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/NJxWBCjC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/0B5EEQbS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/FV4EmCxR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/xNhG0I6b',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/MN4iTKpY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/wJxWUALI',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/8B4GhCAT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/xZ40EAAT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/wFgmjIjQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/IZ4WAYhS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/NJgWzKSS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/dYwyAYZD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/dc4QkYDA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/cI5ACKYY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/lBwWVQxZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/VJ4ACahY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/5BhA0KzK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/AE4A3KYI',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/oAowXQrS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/gUoEEAxK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/NE4iGKQK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/EBwgCahK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/FNowjSQL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/FR4SiK4b',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/wNgkBCKK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/QJ4yRYBD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/tBhkEA5Y',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/YEgmmKbb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/FNwGzAzQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/wBo2wAbY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/gJ400KbT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/RIoEAawB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/NZ5GWQqI',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/1d4UUaoT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/cI5m3SCJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/1QgwGADC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/lRo0gITD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/8AxwXQLI',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/MJpWVArL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/UVgSWS6Q',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/UV5kGaJa',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/lNoyGIRA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/RYpgxAjL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/5QoGFABY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/EUwwWIbD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/BAgATa7a',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/cBgEQKDI',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/dQgAQKQS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/0Ygm0YiL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/wZ5gmAyY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/gEpywQBD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/lMhS0ApB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/9NoiBKrQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/RYxCVCaY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/hFgWVSzQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/ZUhk1K4C',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/oQwmCQZL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/pQpG0CDD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/dIh0GKzZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/9AgmnAjD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/IAgGwArA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/sBxUgCKS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/ZIpUHYIZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/MJoSiQab',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/wZxm3ATJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/ZUoy1Ypb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/VU5kHCCC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/9BgEhaIR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/dNgAzSBS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/hExyDYQZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/gMog2QSJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/UVwkmISK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/MMgAmYAQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/BIhUCIhT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/4F4yDKBY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/JAoQTQRJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/sIxCCCAC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/UB40UC7a',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/BRxQSIpK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/4UpGxQpD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/1UhgEIgZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/1IhW2agR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/cNwUiQjZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/JcxwUADD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/oYhEWSrb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/9coS1YjK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/tV4SUIYT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/EEoWXKAA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/5Ew0ESIY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/URwUFQIS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/VEoSRawZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/RA4i3KaC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/dQhAhKSK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/0Q5Q2YhI',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/FQoEWCgQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/EdwkFY4Q',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/ZMhkiAAK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/kcwECKKZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/UQxEwKrL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/pV5STAwR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/VdwG0QxK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/sFg0UQyI',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/1IxG2KIT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/kVhWzCrI',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/5YhmgKgS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/5MxGmKZS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/9NhyQaSD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/kN42CA7S',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/lMoCGAKD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/gc5myazS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/oNoExIbL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/odxklSQR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/kAgWHCYC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/MUw0SISZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/dBoQQYQJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/BdoWXABZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/tVgGWAJD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/REgG1Kja',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/4VommSiY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/RJpmhYqT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/oZ4SHCYb',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/schAhKya',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/VMwgESbS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/xVhCBKaS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/AJog2agC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/kNhGhagA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/VJgSBAzA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/8U4CzKaJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/hFhQWAja',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/kRhkxA7I',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/0IgklIwD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/gFo2CYrJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/ZAx2nADD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/sYgwlAaB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/xN4GAYJA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/ZF4g3IJB',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/gZxkmSgA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/IMoWQSAR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/0FoQTAra',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/IMw0VIhS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/ZUwA1CyC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/tIhkiKrZ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/8I5kUCwQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/IQxgnaQQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/FZoUhSAA',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/NYxmhYSR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/8BogRSQL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/hR4EiCgD',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/AYwwGAZC',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/FZxmUSaY',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/pc5UiQrT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/xYpy1YyL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/QZ4AGAbL',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/sEx0hSwJ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/4YgiRIZQ',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/xY4giIBI',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/cU5ASCRK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/cZg03SAK',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/kchmkCyS',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/wN5QFIBR',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/0FwgEC5L',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/JApmQYTT',
'https://mega.nz/folder/cF5xzCLb#bkrCMWy64aLsvfXnwZSjxw/file/5dowDaYD'	
		
		];
		
		
$music_tiles = [];
for ($i = 0; $i < count($titles); $i++) {
    $music_tiles[] = [
        'title' => $titles[$i],
        'youtube_id' => $youtube_ids[$i],
        'mega_link' => $mega_links[$i] ?? '#' // '#' jeśli brak linku
    ];
}

// Przetasuj 
shuffle($music_tiles);

// Kafelki
foreach ($music_tiles as $tile) {
    echo '<div class="music-tile" data-youtube-id="' . $tile['youtube_id'] . '" data-title="' . clean_title($tile['title']) . '">';
    echo '<img src="https://i.ytimg.com/vi/' . $tile['youtube_id'] . '/hqdefault.jpg" alt="' . clean_title($tile['title']) . '" loading="lazy">';
    echo '<div class="title">' . clean_title($tile['title']) . '</div>';
    echo '<a href="' . $tile['mega_link'] . '" class="download-btn" target="_blank">Pobierz</a>';
    echo '</div>';
}
?>
